/**
 * Phase 4A: AI-Powered Insights Engine Types
 *
 * Type definitions for AI-generated insights, metric snapshots,
 * and file references used throughout the insights feature.
 */

/**
 * Type of insight generated by the AI analyzer
 */
export type InsightType = 'improvement' | 'concern' | 'recommendation' | 'prediction';

/**
 * Severity levels for insights
 */
export type InsightSeverity = 'critical' | 'high' | 'medium' | 'low';

/**
 * Trend direction indicator
 */
export type TrendDirection = 'up' | 'down' | 'stable';

/**
 * Metric snapshot showing change over time
 */
export interface MetricSnapshot {
  /** Metric name (e.g., "Quality Score", "Coverage") */
  name: string;
  /** Current value */
  current: number;
  /** Previous value (for comparison) */
  previous: number;
  /** Absolute change (current - previous) */
  change: number;
  /** Percentage change */
  changePercent: number;
  /** Trend direction */
  trend: TrendDirection;
  /** Unit of measurement (e.g., "%", "pts", "issues") */
  unit?: string;
}

/**
 * File reference with optional location details
 */
export interface FileReference {
  /** File path relative to project root */
  path: string;
  /** Line number in the file */
  line?: number;
  /** Code snippet for context */
  snippet?: string;
  /** URL to view file (e.g., GitHub link) */
  url?: string;
  /** Coverage or quality percentage for this file */
  percentage?: number;
  /** Previous percentage (for showing change) */
  previousPercentage?: number;
}

/**
 * AI-generated insight
 */
export interface AIInsight {
  /** Unique identifier */
  id: string;
  /** Type of insight */
  type: InsightType;
  /** Severity/priority level */
  severity: InsightSeverity;
  /** Short, descriptive title */
  title: string;
  /** Detailed explanation in natural language */
  explanation: string;
  /** Confidence score (0-100) */
  confidence: number;
  /** Related metric snapshots */
  metrics: MetricSnapshot[];
  /** Affected files with details */
  affectedFiles: FileReference[];
  /** Actionable recommendations */
  recommendations: string[];
  /** ISO 8601 timestamp when insight was generated */
  createdAt: string;
  /** ISO 8601 timestamp when insight was acknowledged (if any) */
  acknowledgedAt?: string;
  /** User who acknowledged the insight */
  acknowledgedBy?: string;
  /** Category for grouping (e.g., "security", "performance", "testing") */
  category?: string;
  /** Tags for filtering */
  tags?: string[];
}

/**
 * Summary statistics for insights
 */
export interface InsightsSummary {
  /** Total number of insights */
  total: number;
  /** Count by type */
  byType: Record<InsightType, number>;
  /** Count by severity */
  bySeverity: Record<InsightSeverity, number>;
  /** Number of unacknowledged insights */
  unacknowledged: number;
  /** Overall confidence score (weighted average) */
  overallConfidence: number;
  /** AI-generated headline summary */
  headline: string;
  /** ISO 8601 timestamp of last update */
  lastUpdated: string;
}

/**
 * Insights report structure (from Python analyzer)
 */
export interface InsightsReport {
  /** Summary statistics */
  summary: InsightsSummary;
  /** List of all insights */
  insights: AIInsight[];
  /** Key metrics for the hero card */
  keyMetrics: MetricSnapshot[];
  /** Version of the analyzer that generated this report */
  analyzerVersion: string;
  /** ISO 8601 timestamp when report was generated */
  generatedAt: string;
}

/**
 * Filter options for insights
 */
export interface InsightsFilters {
  /** Filter by insight types */
  types?: InsightType[];
  /** Filter by severities */
  severities?: InsightSeverity[];
  /** Filter by categories */
  categories?: string[];
  /** Show only unacknowledged */
  unacknowledgedOnly?: boolean;
  /** Search in title/explanation */
  searchQuery?: string;
  /** Filter by minimum confidence */
  minConfidence?: number;
}

/**
 * Sort configuration for insights
 */
export interface InsightsSortConfig {
  /** Field to sort by */
  field: 'severity' | 'confidence' | 'createdAt' | 'type';
  /** Sort direction */
  direction: 'asc' | 'desc';
}

/**
 * API response for acknowledge action
 */
export interface AcknowledgeResponse {
  /** Success status */
  success: boolean;
  /** Updated insight */
  insight: AIInsight;
  /** Error message if failed */
  error?: string;
}

/**
 * API response for regenerate action
 */
export interface RegenerateResponse {
  /** Success status */
  success: boolean;
  /** Newly generated insights */
  insights: AIInsight[];
  /** Processing time in milliseconds */
  processingTime: number;
  /** Error message if failed */
  error?: string;
}
