/**
 * Route Tree (Generated by TanStack Router)
 *
 * This file is normally auto-generated by the TanStack Router CLI.
 * Run `npm run routes:generate` to generate this file automatically.
 *
 * For now, this is a manual implementation for development.
 * In production, use the TanStack Router CLI to generate this file.
 *
 * To set up auto-generation:
 * 1. Install: npm install -D @tanstack/router-cli
 * 2. Add to package.json scripts:
 *    "routes:generate": "tsr generate"
 *    "routes:watch": "tsr watch"
 * 3. Add tanstack.config.json configuration
 */

import { Route as rootRoute } from './routes/__root';
import { Route as dashboardRoute } from './routes/dashboard/index';

/**
 * Route tree structure
 *
 * Manually constructed route tree for development.
 * In production, this would be auto-generated from route files.
 */
const rootRouteWithChildren = rootRoute.addChildren([
  dashboardRoute,
]);

/**
 * Export the complete route tree
 */
export const routeTree = rootRouteWithChildren;

/**
 * Type-safe route configuration
 */
export type RouteTree = typeof routeTree;
